- table_name: filemanagement
  columns:
    - name: file_id
      type: INT
    - name: filename
      type: VARCHAR(255)
    - name: extension
      type: VARCHAR(10)
    - name: file_hierarchy
      type: VARCHAR(255)
    - name: file_source_path
      type: VARCHAR(255)
    - name: file_source
      type: VARCHAR(255)
    - name: metadata
      type: TEXT
    - name: file_size
      type: VARCHAR(10)
- table_name: datahierarchy
  columns:
    - name: id
      type: SERIAL PRIMARY KEY
    - name: parent_id
      type: INT
    - name: name
      type: VARCHAR(255)
    - name: FOREIGN KEY (parent_id)
      type: REFERENCES {schema}.datahierarchy(id) ON DELETE CASCADE